//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlertToolsEntities : DbContext
    {
        public AlertToolsEntities()
            : base("name=AlertToolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerComponentsDetail> CustomerComponentsDetails { get; set; }
        public virtual DbSet<DeliveryLateness> DeliveryLatenesses { get; set; }
        public virtual DbSet<DrawingLateness> DrawingLatenesses { get; set; }
        public virtual DbSet<HistoryIssue> HistoryIssues { get; set; }
        public virtual DbSet<HistoryIssueUser> HistoryIssueUsers { get; set; }
        public virtual DbSet<IssueHeader> IssueHeaders { get; set; }
        public virtual DbSet<LateDrawingLog> LateDrawingLogs { get; set; }
        public virtual DbSet<MachineBreakdownDetail> MachineBreakdownDetails { get; set; }
        public virtual DbSet<MachineBreakdownLog> MachineBreakdownLogs { get; set; }
        public virtual DbSet<MasterIssue> MasterIssues { get; set; }
        public virtual DbSet<MaterialIssueDetail> MaterialIssueDetails { get; set; }
        public virtual DbSet<MaterialIssueLog> MaterialIssueLogs { get; set; }
        public virtual DbSet<MaterialProcurementPOTracking> MaterialProcurementPOTrackings { get; set; }
        public virtual DbSet<QualityControlPOTracking> QualityControlPOTrackings { get; set; }
        public virtual DbSet<QualityReceivePOTracking> QualityReceivePOTrackings { get; set; }
        public virtual DbSet<ReceiverPrivilege> ReceiverPrivileges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<AlertNotification> AlertNotifications { get; set; }
    }
}
