//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETAHistory
    {
        public int ID { get; set; }
        public int PurchasingDocumentItemID { get; set; }
        public Nullable<int> DelayReasonID { get; set; }
        public Nullable<System.DateTime> ETADate { get; set; }
        public Nullable<bool> AcceptedByProcurement { get; set; }
        public string ETADescription { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual DelayReason DelayReason { get; set; }
        public virtual PurchasingDocumentItem PurchasingDocumentItem { get; set; }
    }
}
