//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssueHeader()
        {
            this.AlertNotifications = new HashSet<AlertNotification>();
            this.CustomerComponentsDetails = new HashSet<CustomerComponentsDetail>();
            this.DeliveryLatenesses = new HashSet<DeliveryLateness>();
            this.DrawingLatenesses = new HashSet<DrawingLateness>();
            this.HistoryIssues = new HashSet<HistoryIssue>();
            this.HistoryIssueUsers = new HashSet<HistoryIssueUser>();
            this.MachineBreakdownDetails = new HashSet<MachineBreakdownDetail>();
            this.MaterialIssueDetails = new HashSet<MaterialIssueDetail>();
            this.MaterialProcurementPOTrackings = new HashSet<MaterialProcurementPOTracking>();
            this.QualityControlPOTrackings = new HashSet<QualityControlPOTracking>();
            this.QualityReceivePOTrackings = new HashSet<QualityReceivePOTracking>();
        }
    
        public int ID { get; set; }
        public int MasterIssueID { get; set; }
        public string RaisedBy { get; set; }
        public Nullable<int> Raiser { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IssueDescription { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ClosedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertNotification> AlertNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerComponentsDetail> CustomerComponentsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryLateness> DeliveryLatenesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawingLateness> DrawingLatenesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryIssue> HistoryIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryIssueUser> HistoryIssueUsers { get; set; }
        public virtual MasterIssue MasterIssue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineBreakdownDetail> MachineBreakdownDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialIssueDetail> MaterialIssueDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProcurementPOTracking> MaterialProcurementPOTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityControlPOTracking> QualityControlPOTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityReceivePOTracking> QualityReceivePOTrackings { get; set; }
    }
}
