//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineBreakdownDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MachineBreakdownDetail()
        {
            this.MachineBreakdownLogs = new HashSet<MachineBreakdownLog>();
        }
    
        public int ID { get; set; }
        public int IssueHeaderID { get; set; }
        public int MachineTypeID { get; set; }
        public Nullable<System.DateTime> ServiceTime { get; set; }
        public Nullable<System.DateTime> SparePartTime { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual IssueHeader IssueHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineBreakdownLog> MachineBreakdownLogs { get; set; }
    }
}
