//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialIssueLog
    {
        public int ID { get; set; }
        public int MaterialIssueID { get; set; }
        public string UpdatedParameter { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual MaterialIssueDetail MaterialIssueDetail { get; set; }
    }
}
