//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialIssueDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialIssueDetail()
        {
            this.MaterialIssueLogs = new HashSet<MaterialIssueLog>();
        }
    
        public int ID { get; set; }
        public int IssueHeaderID { get; set; }
        public string PartNumberComponent { get; set; }
        public Nullable<System.DateTime> EndDateEstimation { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string PRONumber { get; set; }
        public int Quantity { get; set; }
        public string PRNumber { get; set; }
        public string PONumber { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual IssueHeader IssueHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialIssueLog> MaterialIssueLogs { get; set; }
    }
}
