//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public int PurchasingDocumentItemID { get; set; }
        public int StatusID { get; set; }
        public string Stage { get; set; }
        public string Role { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> GoodsReceiptDate { get; set; }
        public Nullable<int> GoodsReceiptQuantity { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual NotificationStatu NotificationStatu { get; set; }
        public virtual PurchasingDocumentItem PurchasingDocumentItem { get; set; }
    }
}
