//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POTrackingEntities : DbContext
    {
        public POTrackingEntities()
            : base("name=POTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capability> Capabilities { get; set; }
        public virtual DbSet<CapabilityCategory> CapabilityCategories { get; set; }
        public virtual DbSet<DelayReason> DelayReasons { get; set; }
        public virtual DbSet<ETAHistory> ETAHistories { get; set; }
        public virtual DbSet<KompoCategory> KompoCategories { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationStatu> NotificationStatus { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<ProductionSequenceData> ProductionSequenceDatas { get; set; }
        public virtual DbSet<ProgressPhoto> ProgressPhotoes { get; set; }
        public virtual DbSet<PurchasingDocumentItem> PurchasingDocumentItems { get; set; }
        public virtual DbSet<PurchasingDocumentItemHistory> PurchasingDocumentItemHistories { get; set; }
        public virtual DbSet<QualityControlProgress> QualityControlProgresses { get; set; }
        public virtual DbSet<RawMaterialOrderDetail> RawMaterialOrderDetails { get; set; }
        public virtual DbSet<RawMaterialOrderPoFile> RawMaterialOrderPoFiles { get; set; }
        public virtual DbSet<RawMaterialOrderProgressFile> RawMaterialOrderProgressFiles { get; set; }
        public virtual DbSet<RawMaterialOrder> RawMaterialOrders { get; set; }
        public virtual DbSet<RolesType> RolesTypes { get; set; }
        public virtual DbSet<SequencesProgressReason> SequencesProgressReasons { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<SubcontCapability> SubcontCapabilities { get; set; }
        public virtual DbSet<SubcontCategory> SubcontCategories { get; set; }
        public virtual DbSet<SubcontComponentCapability> SubcontComponentCapabilities { get; set; }
        public virtual DbSet<SubcontDevVendor> SubcontDevVendors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserProcurementSuperior> UserProcurementSuperiors { get; set; }
        public virtual DbSet<UserRoleType> UserRoleTypes { get; set; }
        public virtual DbSet<UserVendor> UserVendors { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
