//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementVendorRelationship
    {
        public int ID { get; set; }
        public string ProcurementUsername { get; set; }
        public string VendorCode { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
