//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionSequenceData
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int SequenceDate { get; set; }
        public string Document { get; set; }
        public int SequenceCategoryID { get; set; }
        public int PurchasingDocumentsItemID { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual PurchasingDocumentItem PurchasingDocumentItem { get; set; }
    }
}
