//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityReceivePOTracking
    {
        public int ID { get; set; }
        public int IssueHeaderID { get; set; }
        public string PONumber { get; set; }
        public string PRNumber { get; set; }
        public string PartNumber { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> MovementType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual IssueHeader IssueHeader { get; set; }
    }
}
