//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiverPrivilege
    {
        public int ID { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<bool> ArrivalDate { get; set; }
        public Nullable<bool> ServiceDate { get; set; }
        public Nullable<bool> PRNumber { get; set; }
        public Nullable<bool> PONumber { get; set; }
        public Nullable<bool> Quantity { get; set; }
        public Nullable<bool> FinishDate { get; set; }
        public Nullable<bool> SparepartDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string ModifiedBy { get; set; }
        public string Modified { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
