//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ID { get; set; }
        public int PurchasingDocumentItemID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> ATDDate { get; set; }
        public Nullable<System.DateTime> CopyBLDate { get; set; }
        public string CopyBLDocument { get; set; }
        public string PackingListDocument { get; set; }
        public string InvoiceDocument { get; set; }
        public string AWB { get; set; }
        public string CourierName { get; set; }
        public Nullable<System.DateTime> ETADate { get; set; }
        public Nullable<System.DateTime> ATADate { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual PurchasingDocumentItem PurchasingDocumentItem { get; set; }
    }
}
