//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubcontComponentCapability
    {
        public int ID { get; set; }
        public string VendorCode { get; set; }
        public bool isNeedSequence { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public int DailyLeadTime { get; set; }
        public int MonthlyLeadTime { get; set; }
        public int PB { get; set; }
        public int Setting { get; set; }
        public int Fullweld { get; set; }
        public int Primer { get; set; }
        public decimal MonthlyCapacity { get; set; }
        public decimal DailyCapacity { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
