//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTrackingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.POes = new HashSet<PO>();
            this.SubcontCapabilities = new HashSet<SubcontCapability>();
            this.SubcontComponentCapabilities = new HashSet<SubcontComponentCapability>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string Address { get; set; }
        public string CorporateGroup { get; set; }
        public string AccountGroup { get; set; }
        public string Telephone1 { get; set; }
        public string FaxNumber { get; set; }
        public string Plant { get; set; }
        public Nullable<int> SubcontCategoryID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO> POes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubcontCapability> SubcontCapabilities { get; set; }
        public virtual SubcontCategory SubcontCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubcontComponentCapability> SubcontComponentCapabilities { get; set; }
    }
}
